name: Test Template
on:
  workflow_call:
    inputs:
      env: { required: true, type: string }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm test