name: TechMarket Main Pipeline
on:
  push:
    branches: [ main ]
jobs:
  Build:
    uses: ./.github/workflows/template_build.yml
    with: { node-version: '20' }
  Test:
    needs: Build
    uses: ./.github/workflows/template_test.yml
    with: { env: 'staging' }
  Deploy:
    needs: Test
    uses: ./.github/workflows/template_deploy.yml
    with: { bucket-name: 'ignacio-techmarket-2026' }
    secrets:
      # Pasamos los secretos usando los nombres exactos que configuraste
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}